name: CI

on: [push]

jobs:
  check-code:
    name: Check code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64
      - name: Install dependencies
        run: |
          sudo apt-get install clang-format cppcheck
          pip install -r requirements.txt
      - name: Check code quality
        run: make check
  test-linux:
    runs-on: ubuntu-20.04
    name: Test on Linux
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64
      - name: Install dependencies
        run: |
          sudo apt-get install libboost-all-dev
          pip install -r requirements.txt
      - name: Build and run tests
        run: make test
  test-macos:
    runs-on: macos-10.15
    name: Test on MacOS
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64
      - name: Install dependencies
        run: |
          brew install boost
          pip install -r requirements.txt
      - name: Build and run tests
        run: make test
  test-windows:
    runs-on: windows-2019
    name: Test on Windows
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1
      - name: Install dependencies
        run: |
          (New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/zlib.install/master/install.bat', 'install.bat'); ./install.bat
          pip install -r requirements.txt
      - name: Build and run tests
        run: |
          $env:BOOST_ROOT=$env:BOOST_ROOT_1_72_0
          make test-windows
