name: CI

on: [push]

jobs:
  check-code:
    name: Check code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64
      - name: Install dependencies
        run: |
          sudo apt-get install clang-format cppcheck
          pip install -r requirements.txt
      - name: Check code quality
        run: make check
  test-linux:
    runs-on: ubuntu-20.04
    name: Test on Linux
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build and run tests
        run: make test
  test-macos:
    runs-on: macos-10.15
    name: Test on MacOS
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build and run tests
        run: make test
  test-windows:
    runs-on: windows-2019
    name: Test on Windows
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build and run tests
        run: make test-windows
  # test-linux:
  #   runs-on: ubuntu-20.04
  #   name: Test on Linux
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@master
  #     - name: Build and run tests
  #       run: |
  #         docker run --rm dockbuild/centos5:latest > ./dockbuild
  #         chmod +x ./dockbuild
  #         ./dockbuild bash -c "make test"
  # test-macos:
  #   runs-on: macos-10.15
  #   name: Test on MacOS
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@master
  #     - name: Build and run tests
  #       run: make test
  # test-windows:
  #   runs-on: ubuntu-20.04
  #   name: Test on Windows
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@master
  #     - name: Build and run tests
  #       run: |
  #         docker run --rm dockcross/windows-static-x64:20200609-7fa7213 > ./dockcross
  #         chmod +x ./dockcross
  #         ./dockcross bash -c "sudo ln -s /usr/bin/make /usr/bin/gmake && make test"
