name: Release

on:
  release:
    types: [published]

jobs:
  build-linux:
    name: Build linux
    runs-on: ubuntu-20.04
    env:
      RELEASE_OS: linux
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup environment
        id: setup
        run: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF##*/}
      - name: Install dependencies
        run: sudo apt-get install zlib1g-dev libboost-all-dev
      - name: Build and compile release
        run: |
          make build
          make compile-release
        env:
          RELEASE_VERSION: ${{ steps.setup.outputs.RELEASE_VERSION }}
      - name: Upload to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/lfq_${{ env.RELEASE_OS }}-${{ steps.setup.outputs.RELEASE_VERSION }}.tar.gz
          asset_name: lfq_${{ env.RELEASE_OS }}-${{ steps.setup.outputs.RELEASE_VERSION }}.tar.gz
          tag: ${{ github.ref }}

  build-mac:
    name: Build mac
    runs-on: macos-latest
    env:
      RELEASE_OS: mac
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup environment
        id: setup
        run: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF##*/}
      - name: Install dependencies
        run: brew install boost
      - name: Build and compile release
        run: |
          make build
          make compile-release
        env:
          RELEASE_VERSION: ${{ steps.setup.outputs.RELEASE_VERSION }}
      - name: Upload to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/lfq_${{ env.RELEASE_OS }}-${{ steps.setup.outputs.RELEASE_VERSION }}.tar.gz
          asset_name: lfq_${{ env.RELEASE_OS }}-${{ steps.setup.outputs.RELEASE_VERSION }}.tar.gz
          tag: ${{ github.ref }}

  build-windows:
    name: Build windows
    runs-on: ubuntu-20.04
    env:
      RELEASE_OS: windows
      DOCKCROSS_IMAGE: dockcross/windows-static-x64:20200609-7fa7213
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup environment
        id: setup
        run: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF##*/}
      - name: Build
        run: |
          docker run --rm $DOCKCROSS_IMAGE > ./dockcross
          chmod +x ./dockcross
          ./dockcross -a "-e RELEASE_OS=$RELEASE_OS -e RELEASE_VERSION=$RELEASE_VERSION" bash -c "make install-zlib -f Makefile.dockcross && make install-boost -f Makefile.dockcross && make build && make compile-release-windows"
        env:
          RELEASE_VERSION: ${{ steps.setup.outputs.RELEASE_VERSION }}
      - name: Upload to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/lfq_${{ env.RELEASE_OS }}-${{ steps.setup.outputs.RELEASE_VERSION }}.zip
          asset_name: lfq_${{ env.RELEASE_OS }}-${{ steps.setup.outputs.RELEASE_VERSION }}.zip
          tag: ${{ github.ref }}
